baseURL: https://blog.bear-su.dev
disablePathToLower: true
languageCode: en-us
title: Bear Su's Blog
copyright: "Copyright © 2015 - 2024 Bear Su's Blog"

theme: simplecss
contentDir: content/posts
enableRobotsTXT: true

# https://jdhao.github.io/2019/12/29/hugo_html_not_shown/
markup:
  defaultMarkdownHandler: "goldmark"
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    endLevel: 6
    ordered: false
    startLevel: 2
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    noHl: false
    style: monokai
    tabWidth: 4

googleAnalytics: "G-KJXNT5CQCS"

paginate: 200

params:
  description: "Ruby, Web Application and Cloud Services."
  images:
  - images/x-card.png
  author: "Bear Su"
  likerID: "timfanda35"
  logo: "/images/bear.jpeg"
  url: "https://github.com/timfanda35"

taxonomies:
  category: "categories"

menu:
  global:
  - name: "Home"
    url: "/"
    weight: 1
  - name: "Categories"
    url: "/categories/"
    weight: 2
  - name: "Bio Links"
    url: "https://bear-su.dev"
    weight: 3
