baseURL: https://blog.bear-su.dev
disablePathToLower: true
languageCode: en-us
title: Bear Su's Blog
copyright: "Copyright © 2015 - 2023 Bear Su's Blog"

theme: hugo-gentoo-theme-custom
contentDir: content/posts
enableRobotsTXT: true

# https://jdhao.github.io/2019/12/29/hugo_html_not_shown/
markup:
  defaultMarkdownHandler: "goldmark"
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    endLevel: 6
    ordered: false
    startLevel: 2
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    style: monokai
    tabWidth: 4

googleAnalytics: "G-KJXNT5CQCS"

paginate: 10

params:
  description: "Running Bear!!!"
  images:
  - images/x-card.png
  author: "Bear Su"
  likerID: "timfanda35"

taxonomies:
  category: "categories"
  tag: "tags"

menu:
  global:
  - name: "Categories"
    url: "/categories/"
  - name: "GitHub"
    url: "https://github.com/timfanda35"
  - name: "Twitter"
    url: "https://twitter.com/Fandayo"
  - name: "Linkedin"
    url: "https://www.linkedin.com/in/bearsu"
